#!/bin/bash

# Define colors
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
ENDCOLOR="\e[0m"



NETBOOT_DIR="/tmp/run-pixiecore"

# Function to display help/usage information
usage() {
  echo "Usage: $0 {build|start|stop|help} [FILENAME]"
  echo
  echo -e "$RED [ COMMANDS: ] $ENDCOLOR"
  echo -e "$GREEN build FILE $ENDCOLOR   Build the netboot image from the specified Nix file."
  echo -e "$GREEN start $ENDCOLOR        Start the netboot service by configuring iptables and running the image."
  echo -e "$GREEN stop $ENDCOLOR         Stop the netboot service by removing iptables rules."
  echo -e "$GREEN help $ENDCOLOR         Display this help message."
  echo
  echo -e "$RED [ EXAMPLE USAGE: ] $ENDCOLOR"
  echo -e "$GREEN $0 build nixfile.nix $ENDCOLOR      - Build netboot image from the specified Nix file."
  echo -e "$GREEN $0 start $ENDCOLOR                   - Start the netboot service."
  echo -e "$GREEN $0 stop $ENDCOLOR                    - Stop the netboot service."
}

# Check if the first argument is provided
if [ $# -lt 1 ]; then
  usage
  exit 1
fi

# Function to build the netboot image
build() {
  if [ -z "$1" ]; then
    echo "Error: FILENAME_HERE is required for the build command."
    exit 1
  fi
  echo "Building netboot image from $1..."
  nix build -f "$1" -o "$NETBOOT_DIR"
}

# Function to start the netboot service
start() {
  echo "Starting netboot service..."
  sudo iptables -w -I nixos-fw -p udp -m multiport --dports 67,69,4011 -j ACCEPT
  sudo iptables -w -I nixos-fw -p tcp -m tcp --dport 64172 -j ACCEPT
  sudo "$(realpath "$NETBOOT_DIR")"
}

# Function to stop the netboot service
stop() {
  echo "Stopping netboot service..."
  sudo iptables -w -D nixos-fw -p udp -m multiport --dports 67,69,4011 -j ACCEPT
  sudo iptables -w -D nixos-fw -p tcp -m tcp --dport 64172 -j ACCEPT
}

# Main logic to process commands
case "$1" in
  build)
    build "$2"
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  help)
    usage
    ;;
  *)
    echo "Invalid command: $1"
    usage
    exit 1
    ;;
esac
