# .sops.yaml

keys:
  - &desktop age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp
  - &homie age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp
  - &kotte age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp  
  - &laptop age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp
  - &nasty age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp

creation_rules:
  - path_regex: \.yaml$
    key_groups:
      - age:
          - *desktop
          - *nasty
          - *homie
          - *laptop
          - *kotte
      

