version: "3.8"

services:
  caddy-duckdns:
    build: .
    container_name: caddy-duckdns
    ports:
      - "8443:80"
      - "4433:443"
    environment:
      - TZ=America/New_York
      - FREQUENCY=5
      - RECORD_TYPE=A
      - TOKEN=your-duckdns-token
      - SUBDOMAINS=your-domain.duckdns.org
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
